wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_entry', views.add_entry, name='add_entry'),
    path('delete_entry', views.delete_entry, name='delete_entry'),
    path('wiki/random_title', views.random_entry, name='random_entry'),
    path('wiki/<str:title>', views.get_entry, name='TITLE'),
    path('search', views.search, name='search'),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django import forms
from markdown2 import markdown
from . import util
import random


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def get_entry(request, title):
    return render(request, f"encyclopedia/entry.html",{
        "entry": util.get_entry(title),
        "title": title
    })

def add_entry(request):
    if request.method == 'POST':
        print("POST Request")
        title = request.POST.get("title")
        content = request.POST.get("content")
        util.save_entry(title, content)
    return render(request, f"encyclopedia/add_entry.html")

def delete_entry(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        util.delete_entry(title)
    return render(request, f"encyclopedia/delete_entry.html")

def random_entry(request):
    random_number = random.randint(0, len(util.list_entries()) - 1)
    entries = util.list_entries()
    title = entries[random_number]
    entry = util.get_entry(title)
    return render(request, f"encyclopedia/entry.html",{
        "entry": entry,
        "title": title
    })


def search(request):
    q = request.GET.get('q')
    if q in util.list_entries():
        return redirect('encyclopedia:entry', title=q)
    return render(request, "encyclopedia/search.html", {"entries": util.search(q), "q": q})


def entry(request, title):
    entry = util.get_entry(title)
    if entry == None:
        entry = "## Page was not found"
    entry = markdown(entry)
    return render(request, f"encyclopedia/entry.html", {
        "entry": entry, 
        "title": title
    })
    

wiki/encyclopedia/templates/encyclopedia/add_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <center>
        <form method="POST" action = "{% url 'encyclopedia:add_entry'  %}"%>
            {% csrf_token %} 
            <div class='container'>
                <div class='row'>
                    <div class='col-sm-10'>
                        <h1>Add new entry</h1>
                        <input name='title' class='form-control col-sm-8' placeholder='Title' type="text"></br>
                        <textarea name='content' class='form-control' placeholder='Content' style="height:200px;width:600px;"></textarea>
                    </div>
                    </div>
                </div></br>
                <div class='row'>
                    <div class='col-sm-4'></div>
                    <button type='submit' class='btn btn-primary mr-2'>Add</button>
                    <button class='btn btn-danger'>Cancel</button>
                </div>
            </div>
        </form>
    </center>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/delete_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <center>
        <form method="POST" action = "{% url 'encyclopedia:delete_entry' %}"%>
            {% csrf_token %} 
            <div class='container'>
                <div class='row'>
                    
                    <div class='col-sm-10'>
                    <h1>Delete entry</h1>
                        <input name='title' class='form-control col-sm-8' placeholder='Title' type="text"></br>
                    </div>
                    </div>
                </div>

                <div class='row'>
                    <div class='col-sm-5'></div>
                    <center>
                        <button type='submit' class='btn btn-danger mr-2'>Delete</button>
                    </center>
                </div>
            </div>
        </form>
    </center>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <p>{{ entry }}</p>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:TITLE' entry %}">{{ entry }}<a/></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    {% csrf_token %} 
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:delete_entry' %}">Delete Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_entry' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% block nav %} Search {% endblock %}
{% block body %}
<h1>Related Pages</h1>
<p>search result for {{q}}</p>
<ul>
    {% for entry in entries %}
            {% if entry == '-1' %}
                <p>Page not found!</p>
            {% else %}
                <li><a href="{% url 'encyclopedia:TITLE' entry %}">{{ entry }}<a/></li>
            {% endif %}
    {% endfor %}

</ul>

{% endblock %}